spring.application.name=cloud-config-server
server.port=9196

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
# Eureka Instance Configuration
# Hostname ko comment out ya remove kar dein agar IP prefer kar rahe hain
# eureka.instance.hostname=localhost

eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
#add git uri
spring.cloud.config.server.git.uri=https://github.com/CoderWalk/cloud-config-server